version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: menuziapp-laravel
    volumes:
      - app_data:/var/www
      - ./storage:/var/www/storage
      - .env:/var/www/.env
      - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: rapi_delivery_db
      DB_USERNAME: root
      DB_PASSWORD: root
    entrypoint: ["/entrypoint.sh"]

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rapi_delivery_db
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
  app_data: