version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: false
      CACHE_DRIVER: redis
    volumes:
      - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx:
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d